# Generated by Django 5.2.6 on 2025-11-10 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_people_peoplephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('profile_view', 'Profile View'), ('connection_request', 'Connection Request'), ('match', 'New Match'), ('message', 'New Message'), ('like', 'Someone Liked You'), ('custom', 'Custom Message')], default='custom', max_length=20)),
                ('message', models.TextField(help_text='Short message to display to the user')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(help_text='Person this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='app.people')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx')],
            },
        ),
    ]
